version: '3.1'

services:
  postgres_hml:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "@.3ZaJTY!z"
    volumes:
      - ./data_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  postgres_test:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "PEjK@4H.M4"
    volumes:
      - ./data_test:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  postgres_prod:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "L88kfs8_gq"
    volumes:
      - ./data_prod:/var/lib/postgresql/data
    ports:
      - "5434:5432"
