FROM node:lts-alpine
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install --loglevel verbose
RUN npm install -g @adonisjs/cli --loglevel verbose
RUN npm install @adonisjs/mail --loglevel verbose
RUN npm install @adonisjs/ignitor --loglevel verbose
RUN npm install node-cron verbose
RUN npm install socket.io verbose
