version: '3.3'
services:
  app:
    build: .
    image: backend-agenda
    ports:
      - "3333:3333"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
    command: sh -c "adonis serve --dev || tail -f /dev/null"
