version: '3.3'

services:
  app:
    build: .
    image: backend-agenda
    ports:
      - "3333:3333"
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=minhasenha123
      - REDIS_DB=0
    volumes:
      - .:/usr/src/app
    command: sh -c "npm start || tail -f /dev/null"
    depends_on:
      - redis

  redis:
    image: redis:latest
    command: redis-server --requirepass minhasenha123
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=minhasenha123
    volumes:
      - redis-data:/data

volumes:
  redis-data:
